### PR TITLE
Move Compress and Uncompress to compression.go

### PR DESCRIPTION
**Pull request by yznima**
Simple copying of compression code to a new file to allow further refactoring of encode.go and decode.go

### CODE REVIEW

**Comment by sv** [comment]
What is your plan on further refactoring that needs separating compression to separate file?
More idiomatic name would be compress.go

**Comment by yznima** [comment]
@sv 

> What is your plan on further refactoring that needs separating compression to separate file?

See #15

**Comment by yznima** [comment]
@sv Addressed all comments

**Comment by yznima** [comment]
@sv ready for review

**Pull request merged**
